# permissions for end users to view podmigrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: my-criu-migration-operator
    app.kubernetes.io/managed-by: kustomize
  name: podmigration-viewer-role
rules:
- apiGroups:
  - migration.example.com
  resources:
  - podmigrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - migration.example.com
  resources:
  - podmigrations/status
  verbs:
  - get
